import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/redux/provider";
import { Header } from "@/components/layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="flex flex-col min-h-screen">
        <ReduxProvider>
          <Header />
          <main className="flex-1 relative z-0">{children}</main>
        </ReduxProvider>
      </body>
    </html>
  );
}
